[package]
name = "advent-of-code-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.92"
quote = "1.0.37"
regex = "1.11.1"
syn = "1.0.109"

[lib]
proc-macro = true
